import { useState } from "react";
import { useStore } from "../store/useStore";
import { uid } from "../store/sampleData";
import { AppRule, Profile } from "../types";
import { Button, Card, Field, IconButton, Input, Modal, PageIntro, Select } from "../components/ui";
import { Icon } from "../components/Icon";

function newProfile(): Profile { return { id:uid("prof"), name:"New profile", icon:"profiles", appRules:[], createdAt:Date.now() }; }
export function Profiles(){ const data=useStore((s)=>s.data); const active=useStore((s)=>s.activeProfileId); const setActive=useStore((s)=>s.setActiveProfile); const add=useStore((s)=>s.addProfile); const update=useStore((s)=>s.updateProfile); const remove=useStore((s)=>s.deleteProfile); const duplicate=useStore((s)=>s.duplicateProfile); const setDefault=useStore((s)=>s.setDefaultProfile); const addRule=useStore((s)=>s.addAppRule); const removeRule=useStore((s)=>s.removeAppRule); const [editing,setEditing]=useState<Profile|null>(null); const [ruleExe,setRuleExe]=useState(""); const [ruleMode,setRuleMode]=useState<AppRule["mode"]>("assign");
  return <div className="content"><PageIntro eyebrow="contexts" title="Profiles" description="Create different shortcut environments for coding, design, gaming, school, browser work, or editing. App rules can switch profiles automatically when a matching app is active."><Button variant="primary" icon="create" onClick={()=>setEditing(newProfile())}>New profile</Button></PageIntro><div className="grid cards-grid">{data.profiles.map((p)=>{ const count=data.shortcuts.filter((s)=>s.profileId===p.id).length; return <Card key={p.id} hover><div className="spread"><span className="profile-icon"><Icon name={p.icon??"profiles"}/></span><div className="row tiny-gap"><IconButton name="edit" onClick={()=>setEditing(p)}/><IconButton name="copy" onClick={()=>duplicate(p.id)}/><IconButton name="trash" onClick={()=>remove(p.id)} disabled={p.id==="prof-default"}/></div></div><h3>{p.name}</h3><p className="muted tiny">{count} shortcuts · {p.appRules.length} app rules {p.isDefault?"· default":""}</p><div className="row wrap"><Button size="sm" variant={active===p.id?"primary":"secondary"} onClick={()=>setActive(p.id)}>Use now</Button><Button size="sm" variant="ghost" onClick={()=>setDefault(p.id)}>Set default</Button></div><div className="rule-list">{p.appRules.map((r)=><span key={r.id} className="chip"><b>{r.mode}</b> {r.exe}<button type="button" onClick={()=>removeRule(p.id,r.id)}>×</button></span>)}</div></Card>})}</div><Modal open={!!editing} onClose={()=>setEditing(null)} title="Profile" width={640} footer={<><Button variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button><Button variant="primary" onClick={()=>{ if(!editing) return; data.profiles.some((p)=>p.id===editing.id)?update(editing):add(editing); setEditing(null); }}>Save profile</Button></>}>{editing&&<div className="col"><div className="grid cols-2"><Field label="Name"><Input value={editing.name} onChange={(e)=>setEditing({...editing,name:e.target.value})}/></Field><Field label="Icon name"><Input value={editing.icon??"profiles"} onChange={(e)=>setEditing({...editing,icon:e.target.value})}/></Field></div><Card style={{padding:14}}><h3 className="section-title">Add app rule</h3><div className="grid cols-3"><Input placeholder="chrome.exe" value={ruleExe} onChange={(e)=>setRuleExe(e.target.value)}/><Select value={ruleMode} onChange={(v)=>setRuleMode(v as AppRule["mode"])} options={["assign","whitelist","blacklist"].map((m)=>({value:m,label:m}))}/><Button icon="create" onClick={()=>{ if(!ruleExe.trim()||!editing) return; addRule(editing.id,{id:uid("rule"),exe:ruleExe,profileId:editing.id,mode:ruleMode}); setEditing({...editing,appRules:[...editing.appRules,{id:uid("rule-local"),exe:ruleExe,profileId:editing.id,mode:ruleMode}]}); setRuleExe(""); }}>Add</Button></div></Card></div>}</Modal></div>;
}
